
# This is the configuration file for the workfow with sections for the individual rules. Adjust to your needs.
# Note that the tmp/ directory is used extensively. On many servers the user's home directory, and hence the standard temp/ directory is too small to be suitable.
# Specify the tmp/ directory in the abra2 options below. (This tmp/ directory will be used by all other rules as well)


################# SAMPLES #############################################
samples: "metadata/sample2runlib.csv"

# Input fastq files and sample metadata are specified in metadata/sample2runlib.csv. Edit this file accordingly.
# Note that entries in columns "run" + "library" together make up the primary key for fastq file location and each combination has to be unique.
# The paths to interleaved fastq input files are specified in column "il_fastq", otherwise in columns fq1 and fq2.
# Separate run/library combinations are joined into samples by identical entries in the "sample" column.

# sample sets are specified as *.txt files in metadata/samplesets.
# There can be several, the placeholder "all_samples" will trigger the respective rule to run on all samples from all files together.

########### REFERENCE GENOME FILE(S) locations ##########################
# Specify the path(s) to your reference genome assembly file(s) (fasta: .fa or .fna) and give them each a name.
# The workflow will look for the required associated files (i.e., .fai, .amb, .ann, .bwt, .pac, .sa) in same directory of the specified fasta file.
# softlinks are possible and we recommend to softlink the parent directory. (See genomes_and_annotations/readme).

refs:
  GCF_004118075.1_ASM411807v1: genomes_and_annotations/GCF_004118075.1_ASM411807v1/GCF_004118075.1_ASM411807v1_genomic.fna
#  my_reference_genome_2:

######### configuration options for the QC rule ##############################
# Adapter "_DEFAULT_" will be used. Replace with your respective adapter sequences, don't remove output related options from "extra"!

qc:
  _DEFAULT_:
    adapter1: CTGTCTCTTATACACATCTCCGAGCCCACGAGACNNNNNNNNATCTCGTATGCCGTCTTCTGCTTG
    adapter2: CTGTCTCTTATACACATCTGACGCTGCCGACGANNNNNNNNGTGTAGATCTCGGTGGTCGCCGTATCATT
    minqual: 25
  Truseq:
    adapter1: AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG
    adapter2: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT
    minqual: 25
  Nextera:
    adapter1: CTGTCTCTTATACACATCTCCGAGCCCACGAGACNNNNNNNNATCTCGTATGCCGTCTTCTGCTTG
    adapter2: CTGTCTCTTATACACATCTGACGCTGCCGACGANNNNNNNNGTGTAGATCTCGGTGGTCGCCGTATCATT
    minqual: 25

  extra: "--combined-output --interleaved --interleaved-output --trimns --trimqualities --trimwindows 10"


########## INDEL REALIGNMENT - ABRA2 ########################################
# configuration options for the indel realigner abra2. this is also the place to specify the location of the tmp file.

abra2:
  memory:
    - Xmx24g
  release:
    - envs/abra2.jar
  temp:
    - /data/norman/tmp/
  threads:
    - 10
  regions:
    - metadata/contigs_of_interest.bed

#TODO move temp variable because other tools are using it as well!

########## VARCALL ############################################################
# configure options for the varcall rules: which aligners and callers to use as well as their parameters
# this is also the place to configure the filters to run on the vcf file to produce filtered vcf file(s).

varcall:
  aligners:
    - bwa
    - ngm
  callers:
  #- mpileup
    - freebayes
  refs:
    - GCF_004118075.1_ASM411807v1
#    - my_reference_genome_2
  samplesets:
#    - mutants
#    - wild_type
    - all_samples
# Paramters
  minmapq:
    bwa: 30
    ngm: 10
  minbq: 15
  theta_prior: 0.001 # default for freebayes is 0.001, make sure you read the respective manuals
  chunksize: 10000000 # it is in these-sized-chunks that freebayes runs. This is implemented for better parallelisation
# Variant Filters. Adjust to your requirements and/or add new ones.
  filters:
    default: >
      -i 'QUAL >= 10 &&
          ALT != "." &&
          INFO/DP >= 5 &&
          INFO/AN >= 3'
    strict: >
      -i 'QUAL >= 40 &&
          ALT != "." &&
          INFO/DP >= 20 &&
          ((INFO/AN / N_SAMPLES)*2) > 0.20 &&
          MAF >= 0.01'
    # Above strict requires a presence rate of >20%, which isn't ideal when running on more than 1 mutant vs wild-type. Read the respective manual (bcftools view) and ajust

######## ANNOTATION #########################################################
# configuration options for the snpEff rule:
# Your snpeff directory is expected to reside in genomes_and_annotations/snpeffdata, but can be changed in snpEff.config.
# Prior to running the workflow, create/place the snpEff database (snpEffectPredictor.bin) in the same directory. An example is in genomes_and_annotations/readme.
# Currently, only one reference genome can be used at a time. Obviously, the snpeff 'database' must match the reference genome ('ref').
# 'filter' refers to the input vcf file and hence defines the desired variant filter to use upstream of snpeff (compare varcall:filters:).

snpeff:
  ref: GCF_004118075.1_ASM411807v1
  database: GCF_004118075.1_ASM411807v1_snpeff
## experimental for more than one snpeff library
#  genomes:
#    - genome_1
#      ref: genome_1.fa
#      database: genome_1_snpeff_annotation
#    - genome_2
#      ref: genome_2.fa
#      database: genome_2_snpeff_annotation
  samplesets:
#    - mutants
#    - wild_type
    - all_samples
  aligners:
    - bwa
#    - ngm
  callers:
    - freebayes
#    - mpileup
  filters:
    - strict

#TODO: change so that more than one reference genome annotation can be used (will require to jointly specify ref, database, contigs of interest)
#TODO: add rule that prepares the reference genome and annotation for SNPEFF


######## DE NOVO ############################################################
# configure options when runnign the de-novo rule. This is unrelated to any mapping or varcalling. For normal application, leave as is.
denovodist:
  kwip_sketchsize: 1e9
  mash_sketchsize: 1e5
  sourmash_sketchsize: 100000
  ksize: 21
  kwip_sets:
    - all_samples
  mash_sets: # we can subset from everything for (sour)mash
    - all_samples
  sourmash_sets: []


##############################################################################
#EXPERT options below
##############################################################################
# configuration options for the mapping rule. Using those will only have an effect when runnign the mapping rule separately, which is not a recommended use case.
#When the mapping rules is invoked through the varcall rule, the parameters specified in the varcall section above take precedence/are used.
mapping:
  aligners:
    - bwa
#    - ngm
  refs:
    - my_reference_genome_1
#    - my_reference_genome_2
  samplesets:
    - all_samples
  ngm:
    sensitivity: 0.5

# alignment rule
#additional samples for alignment rule only (in addition to samplesets)
align:
    sample_sets: []

################################################################################
#below is not yet implemented

# the mode feature is not yet implemented
# mode: s or c
#   s = samples
#   c = cohort
mode: s

known_variants:
  # Optional: Path to a VCF file of known variants. Variant IDs from this file will be transferred to the new VCF file
  # known-variants: genomes_and_annotations/my_reference_genome_1/known_variants.vcf.gz
  #this feature is currently not yet implemented
  # TODO implement "vcf annotate rule", obviously only meaningful for the exact reference genome of the known_variants file (i.e., implementation for more than one reference genome requires thought, -> do similar to snpeff!)

LB-impute:
  mem: Xmx3g
  release: envs/LB-Impute.jar
  method: impute
  extra: "-readerr  0.05 -genotypeerr 0.05 -recombdist 1000000 -window 5 -offspringimpute "
  parents: "D2,con"
